---
title: "explore combined pesticide data"
author: "Jonathan Jupke"
format: html
execute:
        echo: false
        message: false
editor: visual
---

```{r setup, message = FALSE}
source("../../../R/packages.R")
```

```{r}
data = readRDS("../../../data/combined_data.rds")
```

How many samples?

```{r}
uniqueN(data$sample_id)
```

How many sites?

```{r}
uniqueN(data$site_id)
```

How many samples per site?

```{r}
data[, n.sample := uniqueN(sample_id), by = "site_id"]
sites <- unique(data, by = "site_id")
sites |> ggplot(aes(n.sample)) + geom_histogram(binwidth = 2)
```

When does sampling occur?

```{r}
samples <- unique(data, by = "sample_id")
samples |> ggplot(aes(date)) + geom_histogram()
```

How many compounds per sample?

```{r}
data[, n.compound := uniqueN(compound), by = "sample_id"]
samples <- unique(data, by = "sample_id")
samples |> ggplot(aes(n.compound)) + geom_histogram(binwidth = 2)
```

How many different compounds?

```{r}
uniqueN(data$compound)
```

How often does each compound occur?

```{r}
data[, n.occur := uniqueN(sample_id), by = "compound"]
unique(data, by = "compound") |> dplyr::arrange(desc(n.occur)) |> slice_head(n = 30) |> ggplot(aes(n.occur, reorder(compound, n.occur, sum))) + geom_col(aes(fill = data.set)) + ggtitle("30 compounds w most measurements")
```

```{r}
# all_compounds <- unique(data, by = "compound") |> 
#         arrange(desc(n.occur)) |> 
#         select(compound, n.occur) 
# kable(all_compounds, booktabs = TRUE) %>%
#   kableExtra::kable_styling(font_size = 8)
```

Map of samples

```{r}
sites.sf <- st_as_sf(sites, coords = c("x.coord", "y.coord"), crs = "EPSG:3035")
mapview(sites.sf, zcol = "n.sample")
```

# Run information

```{r}
sessionInfo()
```
